### ISSUE TITLE
An unhandled exception occured.

### ISSUE THREAD

**Issue by xxyuze** [aritchie/httptransfertasks#10]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] .NET Standard 2.0

## Version of OS(s) listed above with issue
ios 12
win10 1809

## Version of Library
2.0.4

## Actual Behavior

**If you force the program to close when downloading, the next time you open the app and re-download, a native error will occur.**

Task <AD3AD8D1-EC64-4E2E-95C8-FBA0A12585A2>.<7> load failed with error Error Domain=NSURLErrorDomain Code=-999 "(null)" UserInfo={NSURLErrorBackgroundTaskCancelledReasonKey=0, 

_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundDownloadTask <AD3AD8D1-EC64-4E2E-95C8-FBA0A12585A2>.<7>",
    "LocalDownloadTask <AD3AD8D1-EC64-4E2E-95C8-FBA0A12585A2>.<7>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <AD3AD8D1-EC64-4E2E-95C8-FBA0A12585A2>.<7>} [-999]

**Comment by aritchie** [comment]
I see this occur usually when the server returns an error.  I’ll definitely need more details to be able to even make a guess.

Are you using authentication headers?
Does the server support resume?
Does the sample have this problem for you?
Any reproducible sample?

**Comment by aritchie** [comment]
No response or additional info provided
