### ISSUE TITLE
This plugin is throwing error if I install Plugin.HttpTransferTasks version 1.0.0

### ISSUE THREAD

**Issue by GopinathSubramaniam** [aritchie/httptransfertasks#2]
I have getting version compatibility error if I install Plugin.HttpTransferTasks version 1.0.0. Please check the attached screenshot.
![error](https://user-images.githubusercontent.com/4670042/36980964-79eaa766-2051-11e8-96d5-ffa683536825.PNG)

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET 4.5
 - [] PCL

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Current version is pcl based.  I haven’t taken the time to update to net standard yet

**Comment by BerndStoltefuss** [comment]
Hi,

running into the same problem :-/
 It looks like your v2 branch is net standard compatible? Is it ready for release and could you provide an updated nuget-package?

Thanks
