### ISSUE TITLE
Please support .net standard 2.0!!

### ISSUE THREAD

**Issue by JaeWLee** [aritchie/httptransfertasks#3]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [*] UWP
 - [] NET 4.5
 - [*] PCL

## Expected Behaviour
- Please support .net standard 2.0

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Done 2.0 is on nuget
