### ISSUE TITLE
Android Timeout after 100s

### ISSUE THREAD

**Issue by iteufel** [aritchie/httptransfertasks#4]
- [ ] iOS
 - [X] Android
 - [ ] UWP 16299+
 - [X] .NET Standard 2.0

## Version of OS(s) listed above with issue
Any

## Version of Library
2.0.0

## Expected Behaviour
Android File Upload has no timeouts.

## Actual Behavior
Android File Upload Times out after 100s.
https://msdn.microsoft.com/de-de/library/system.net.http.httpclient.timeout(v=vs.110).aspx

**Comment by aritchie** [comment]
Fixed in 2.0.1
