### ISSUE TITLE
[iOS] Request Headers not being sent

### ISSUE THREAD

**Issue by DanielCauser** [aritchie/httptransfertasks#8]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP 16299+
 - [] .NET Standard 2.0

## Version of OS(s) listed above with issue
NA - All iOS versions.

## Version of Library
2.0.1

## Expected Behaviour
The headers property from NSMutableUrlRequest should be set.

## Actual Behavior
When setting up headers on the client side, before performing a download. These Headers are not set when the request hits the API endpoint. 

Me and @dylanberry have checked the iOS implementation since the  Headers property of the NSMutableUrlRequest class is of type NSDictionary is immutable, the values need to be added at creation time.

https://developer.apple.com/documentation/foundation/nsdictionary

**Comment by DanielCauser** [comment]
I have PRed a fix, but I was not able to test it in my local machine yet. Trying to get the solution to build.

Speacial thanks to @Dylanberry for pairing up with me!

**Comment by aritchie** [comment]
I'll fix up the solution now.  It just needs some updates to the libraries

**Comment by aritchie** [comment]
@DanielCauser please try latest master sample and ensure your test case is good.  If it is, I'll push to nuget right away

**Comment by DanielCauser** [comment]
Is this a fix to be included in Shiny?

**Comment by aritchie** [comment]
I've ported it over to my branch.  Yes
